### ISSUE TITLE
Help connecting HTC Vive to the app

### ISSUE THREAD

**Issue by vladikoff** [aframevr/a-painter#100]
Hello, 

I'm trying to use https://aframe.io/a-painter/ with HTC Vive but my Vive is sitting in the Steam VR 'home scene'. Meanwhile the browser goes full screen. 

How do I make the app to go to my Vive headset screen?

I tried in latest Nightly and stable Chrome on Windows 10.

Cheers!

**Comment by vladikoff** [comment]
Some log:

A-Frame Version: 0.3.0  build.js:299:1570
three Version: ^0.76.1  build.js:299:1614
WebVR Polyfill Version: 0.9.15  build.js:299:1667
A-PAINTER Version: 1  main.js:76:5
core:schema:warn Unknown property `hand` for component/system `tracked-controls`. +0ms  build.js:78:666
core:schema:warn Unknown property `hand` for component/system `tracked-controls`. +15ms  build.js:78:666
components:obj-model:warn Material component properties are ignored when a .MTL is provided +53ms  build.js:78:666
THREE.WebGLRenderer 76  build.js:120:30476
OBJLoader: timer startedbuild.js:108
OBJLoader: 70.54msbuild.js:108
OBJLoader: timer startedbuild.js:108
OBJLoader: 20.36msbuild.js:108
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  build.js:122:11340
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  build.js:122:11340
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  build.js:122:11340
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  build.js:122:11340
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  build.js:122:11340
Error: WebGL: texImage2D: Chosen format/type incurred an expensive reformat: 0x1908/0x1401  build.js:122:11340
OBJLoader: timer startedbuild.js:108
OBJLoader: 3.31msbuild.js:108
Error: WebGL: texImage2D: Incurred CPU-side conversion, which is very slow.  build.js:122:11340
Error: WebGL: texImage2D: Incurred CPU pixel conversion, which is very slow.  build.js:122:11340

**Comment by ngokevin** [comment]
Hi, see https://webvr.info/ to get a proper WebVR browser

**Comment by ngokevin** [comment]
https://webvr.info/get-chrome/

**Comment by vladikoff** [comment]
I was trying with Nightly 52.0a1, gonna try with custom Chrome now. 👍

**Comment by vladikoff** [comment]
In the custom Chromium build from https://webvr.info/get-chrome/ the view works 👍 but controllers do not work :(

**Comment by ngokevin** [comment]
Weird, it should. Restart SteamVR, reboot the controllers, stuff like that?

**Comment by vladikoff** [comment]
@ngokevin oh besides `you must turn on the "Enable WebVR" flag in about:flags` I also had to switch: `Gamepad extensions` to `Enabled` (from `Default`). works now!!

**Comment by ngokevin** [comment]
Ah, right. Glad you found that Gamepad switch.
