### ISSUE TITLE
intermittent UploadCare CORS errors when viewing drawings

### ISSUE THREAD

**Issue by ngokevin** [aframevr/a-painter#102]

**Comment by ngokevin** [comment]
https://twitter.com/mrdoob/status/778356301537562624

**Comment by cvan** [comment]
Here's what the Uploadcare team (Cofounder/CTO) had to say: https://twitter.com/mojololol/status/778677260815470593

Not sure how Doob got in that state though. Perhaps, there's some bug in the upload flow? Want to keep this bug open but repurpose it?

**Comment by dmitry-mukhin** [comment]
1. file is unavailable, hence 404
2. it is possible that Uploadcare CDN doesn't set proper CORS headers on 404 request, we'll investigate. But this will not solve the original problem of accessing removed file.

**Comment by ngokevin** [comment]
It was intermittent. I was able to reproduce sometimes, but after some refreshes, it came up. See the file is still available: https://ucarecdn.com/0fd75ffe-b107-4d72-b990-692692853768/

**Comment by dmitry-mukhin** [comment]
@ngokevin it's just still cached on some cdn edges. it will expire.

**Comment by ngokevin** [comment]
OK, I might have to read some docs on how to store it more permanently (I didn't implement this so I wasn't sure of the policies and haven't read the docs). https://github.com/aframevr/a-painter/blob/master/src/main.js#L113

**Comment by dmitry-mukhin** [comment]
https://github.com/aframevr/a-painter/blob/master/src/main.js#L114

this will save the file if autostore is enabled for the project (in Uploadcare dashboard), otherwise you'll have to store the file explicitly.

e.g.: https://github.com/RexMorgan/uploadcare-node/blob/master/lib/main.js#L228

**Comment by ngokevin** [comment]
@dmitry-mukhin Thanks for looking!

@fernandojsg ^ We should enable auto-store at the UploadCare dashboard so paintings don't get expired.

**Comment by fernandojsg** [comment]
cool! thanks for helping with that 👍
