### ISSUE TITLE
Developing brushes without HMD

### ISSUE THREAD

**Issue by msfeldstein** [aframevr/a-painter#124]
So this is an incredible project, and I'd like to see everyone be able to make brushes, not just people who have HMDs and windows.  I was thinking of a separate standalone app that acts as a simple host for brushes.  I was imagining a space that you can trackball around in and which has a few 'quintessential' shapes, such as line, circle, spiral, zigzag, and whatever else floating around you.  You could press a key and have them all "redraw" themselves over time so you can see how your brush looks as its being drawn, and it would live-reload whenever you saved your brush file.  Once you feel comfortable with how it looks there you can drop it in actual a-painter.

I could imagine this being a sample-app that ships in the a-painter project, and you can run it from the command line and pass it a path to a brush file that it will load.

Down the road we could use leap motion, or thespite/mrdoobs webvr emulator, but i think we can get 90% of the benefit like this.

Thoughts??

**Comment by ngokevin** [comment]
Sounds cool, make it happen :)

**Comment by msfeldstein** [comment]
On it.

**Comment by fernandojsg** [comment]
Sounds crazy and cool and the same time, which I like :D :+1:

**Comment by msfeldstein** [comment]
This is overkill for now, you can get the same results using a pre-made json sketch: https://medium.com/@msfeldstein/make-a-vr-paintbrush-in-a-painter-68f802716cf9#.j8zcujazp
