### ISSUE TITLE
Use aframe.io's Google Analytics ID

### ISSUE THREAD

**Issue by cvan** [aframevr/a-painter#128]
I noticed the Google Analytics ID for A-Painter does not match the one https://aframe.io uses. https://aframe.io/painter/ is using `UA-80530812-2`. https://aframe.io uses `UA-24056643-4`.

To whomever set up the A-Painter GA account, are you seeing stats in GA? I could be wrong (especially if you changed the host to aframe.io instead of a-painter.com), but I assume GA events are not coming through because of the host mismatch.

**Comment by cvan** [comment]
Also, see #108 for introducing more instrumentation for GA events.

**Comment by ngokevin** [comment]
Yeah, we're getting stats. It's set up to `https://aframe.io/a-painter`.

**Comment by ngokevin** [comment]
I added everyone

**Comment by cvan** [comment]
Awesome, thanks. I read their FAQ, and just FYI it's impossible to transfer Google Analytics accounts. So, whichever ID you use is permanent and tied to your account. I know because I was trying to move Josh's mozvr.com and aframe.io ones.
