### ISSUE TITLE
Do not show controllers on the ground if disconnected

### ISSUE THREAD

**Issue by cvan** [aframevr/a-painter#130]
If I'm viewing [a drawing](https://aframe.io/a-painter/?url=https://ucarecdn.com/e4d0260a-9157-46d3-aaa6-55c794fecab3/), and I don't have context (know this is a HTC Vive experience), I wouldn't know that this is a controller:

![screen shot 2016-09-21 at 11 04 43 pm](https://cloud.githubusercontent.com/assets/203725/18738356/d9169a90-804f-11e6-9147-af6c0253bce3.png)

And, I may not even have a Vive (see #129) or VR-ready browser.

**Comment by ngokevin** [comment]
https://github.com/aframevr/a-painter/pull/122

**Comment by cvan** [comment]
ah, sweet - sorry didn't see that

**Comment by ngokevin** [comment]
alternative implementation would be to not show them if the rotation is exactly 0,0,0
