### ISSUE TITLE
Splash image on master/locally shrunk

### ISSUE THREAD

**Issue by cvan** [aframevr/a-painter#134]
When I load [http://localhost:8080/webpack-dev-server/](http://localhost:8080/webpack-dev-server/) in Firefox, the Z-position (or scale?) of the splash `OBJ` file seems like it changed to be quite tiny compared to how it looks on https://aframe.io/a-painter/.

I checked the entity, and its `position` and the other markup seems unchanged, but I could be missing something.

<img width="1414" alt="screen shot 2016-09-21 at 11 48 21 pm" src="https://cloud.githubusercontent.com/assets/203725/18739094/e626676e-8055-11e6-98be-021b4998e138.png">
<img width="1414" alt="screen shot 2016-09-21 at 11 48 17 pm" src="https://cloud.githubusercontent.com/assets/203725/18739093/e62273d4-8055-11e6-8ec0-2c2078e03f6a.png">

Any ideas? Is this intentional?

**Comment by cvan** [comment]
Ah, I just noticed the whole stage moved. In any event, the logo is a tad illegible, especially the text under the wordmark.

**Comment by ngokevin** [comment]
for context: camera moves back if you don't have headset so you can view a painting (perhaps should make that also only happen if you're loading a painting)

**Comment by cvan** [comment]
> for context: camera moves back if you don't have headset so you can view a painting (perhaps should make that also only happen if you're loading a painting)

gotcha, makes total sense. and, yeah, would probably special case the splash page.

**Comment by cvan** [comment]
This is fixed now:

![screen shot 2016-10-10 at 6 13 44 pm](https://cloud.githubusercontent.com/assets/203725/19255681/4ac87e82-8f15-11e6-94ba-933b172c68d0.png)
