### ISSUE TITLE
entering fullscreen with orbit controls and w/o headset is broken

### ISSUE THREAD

**Issue by ngokevin** [aframevr/a-painter#141]
Might have to set userHeight to 0?

<img width="1388" alt="screen shot 2016-09-23 at 6 25 35 pm" src="https://cloud.githubusercontent.com/assets/674727/18805155/2ea0101a-81bb-11e6-8a40-2a6b81077c5f.png">

**Comment by fernandojsg** [comment]
Fixed on https://github.com/aframevr/a-painter/pull/142
