### ISSUE TITLE
Allow "tracing"

### ISSUE THREAD

**Issue by darkwing** [aframevr/a-painter#145]
This is probably overly ambitious, but it would be cool if you could load a static image in the "background" (i.e. not as part of the painting) and use it as a guide to draw said image with A-Painter.  That way if someone wants to draw a specific image, they don't have to draw, take off the headset to check out the image, draw some more, take off the headset, etc.

**Comment by fernandojsg** [comment]
Right now you can drag&drop an image from your desktop to a-painter and it will popup in the scene so you can use it as reference. Could it works for your case?

**Comment by darkwing** [comment]
Yes sir, I can fly with that.

**Comment by fernandojsg** [comment]
@darkwing by the way, you can also drop 3d models in 'obj' files so you can use them as reference too :)

**Comment by darkwing** [comment]
I'd try it out but the PC I was sent already blew its power supply so I've been rendered useless. FML.

**Comment by fernandojsg** [comment]
Ouch
