### ISSUE TITLE
A-Frame 0.9.x

### ISSUE THREAD

**Issue by weddingdj** [aframevr/a-painter#255]
I made A-painter work with a-frame 0.9.x but the rotation of the oculus touch controller model is wrong. I made a workaround to adjust the rotation but now the paint strokes start above the model. 

I looked through the source but cannot find the line where I can adjust the starting position of a stroke. Any help would be very much appreciated.

**Comment by fhernand** [comment]
Hi weddingdj, you can try to tweak the vector for the oculus touch controller here: https://github.com/aframevr/a-painter/blob/d30b4397f1a79f64a12e7a67ca74d53233ca1d9d/src/systems/brush.js#L392

**Comment by Utopiah** [comment]
Could be interesting to have an update and do a PR because it seems dearly required. I just tried on the Oculus Quest and couldn't see the controllers nor the background. I was basically only able to paint with one color with one type of brush.

**Comment by novali51** [comment]
Hye there, a WebXR version for the Firefox reality or Oculus Browser on the Quest 2 will be a great walk for humanity ... and for the open source world too ...

**Comment by msub2** [comment]
@dmarcos This can be closed now

**Comment by dmarcos** [comment]
closing as per request
